### PR TITLE
chore: update packages to remove known vulnerabilities

### PR DESCRIPTION
**Pull request by katelynsills**
This PR just updates the packages to remove known vulnerabilities that we've been getting security notices for. It does not try to do anything more than the update.

### CODE REVIEW

**Comment by erights** [comment]
I do not like the parens around single parameters of arrow functions. Did this happen somehow as a result of consolidating our listing?

**Comment by katelynsills** [comment]
> I do not like the parens around single parameters of arrow functions. Did this happen somehow as a result of consolidating our listing?

It's prettier >2.0

**Review by erights — APPROVED** [review]
This PR should follow whatever formatting our consolidated lint is causing. If that includes the parens around single parameter or arrow functions, fine. This is definitely the wrong PR to address that. So LGTM.

**Comment by katelynsills** [comment]
> This PR should follow whatever formatting our consolidated lint is causing. If that includes the parens around single parameter or arrow functions, fine. This is definitely the wrong PR to address that. So LGTM.

I agree it should eventually match the consolidated lint. Our current consolidated lint hasn't updated the eslint and prettier packages, so we will need to deal with this issue there too.

**Pull request merged**
